/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simudesafio;

/**
 *
 * @author javie
 */
public class ComponenteMatriz extends javax.swing.JFrame {

    /**
     * Creates new form ComponenteMatriz
     */
    public ComponenteMatriz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1360, 768));
        setMinimumSize(new java.awt.Dimension(1360, 768));

        jButton4.setText("Atras");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Siguiente");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\javie\\OneDrive\\Documents\\NetBeansProjects\\SimuDesafio\\src\\Images\\boton_atras.png")); // NOI18N
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(51, 51, 51)
                .addComponent(jButton5)
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Atras
        switch(number){
            case 1:
                number--;
                jButton4.setEnabled(false);
                jButton5.setEnabled(true);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_1.png")));
                break;
            case 2:
                number--;
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_2.png")));
                break;
            case 3:
                number--;
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_3.png")));
                break;
            case 4:
                number--;
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_4.png")));
                break;
            case 5:
                number--;
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_5.png")));
                break;
            case 6:
                number--;
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_6.png")));
                break;
            case 7:
                number--;
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_7.png")));
                break;
            case 8:
                number--;
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_8.png")));
                break;
            case 9:
                number--;
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_9.png")));
                break;
            case 10:
                number--;
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_10.png")));
                break;
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Siguiente
        switch(number){
            case 0:
                number++;
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_2.png")));
                break;
            case 1:
                number++;
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_3.png")));
                break;
            case 2:
                number++;
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_4.png")));
                break;
            case 3:
                number++;
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_5.png")));
                break;
            case 4:
                number++;
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_6.png")));
                break;
            case 5:
                number++;
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_7.png")));
                break;
            case 6:
                number++;
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_8.png")));
                break;
            case 7:
                number++;
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_9.png")));
                break;
            case 8:
                number++;
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_10.png")));
                break;
            case 9:
                number++;
                jButton4.setEnabled(true);
                jButton5.setEnabled(false);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Definicion/matriz_definicion_11.png")));
                break;
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComponenteMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComponenteMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComponenteMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComponenteMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComponenteMatriz().setVisible(true);
            }
        });
    }
    
    private int number = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
