/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simudesafio;

/**
 *
 * @author javie
 */
public class PasosMEF extends javax.swing.JFrame {

    /**
     * Creates new form PasosMEF
     */
    public PasosMEF() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1360, 768));
        setMinimumSize(new java.awt.Dimension(1360, 768));
        setPreferredSize(new java.awt.Dimension(1360, 768));

        jButton1.setText("Paso 1");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Paso 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Paso 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Paso 4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Paso 5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Paso 6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Paso 7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Dirichlet");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso1.png"))); // NOI18N

        jButton9.setText("siguiente");
        jButton9.setEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Atras");
        jButton10.setEnabled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton9))
                .addContainerGap())
        );

        jButton11.setIcon(new javax.swing.ImageIcon("C:\\Users\\javie\\OneDrive\\Documents\\NetBeansProjects\\SimuDesafio\\src\\Images\\boton_atras.png")); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Neumann");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton7)
                            .addComponent(jButton8)
                            .addComponent(jButton12)))
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso1.png")));
       jButton1.setEnabled(false);
       jButton2.setEnabled(true);
       jButton3.setEnabled(true);
       jButton4.setEnabled(true);
       jButton5.setEnabled(true);
       jButton6.setEnabled(true);
       jButton7.setEnabled(true);
       jButton8.setEnabled(true);
       jButton9.setEnabled(false);
       jButton10.setEnabled(false);
       jButton12.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso2.png")));
       jButton1.setEnabled(true);
       jButton2.setEnabled(false);
       jButton3.setEnabled(true);
       jButton4.setEnabled(true);
       jButton5.setEnabled(true);
       jButton6.setEnabled(true);
       jButton7.setEnabled(true);
       jButton8.setEnabled(true);
       jButton9.setEnabled(false);
       jButton10.setEnabled(false);
       jButton12.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso3.png")));
       jButton1.setEnabled(true);
       jButton2.setEnabled(true);
       jButton3.setEnabled(false);
       jButton4.setEnabled(true);
       jButton5.setEnabled(true);
       jButton6.setEnabled(true);
       jButton7.setEnabled(true);
       jButton8.setEnabled(true);
       jButton9.setEnabled(false);
       jButton10.setEnabled(false);
       jButton12.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso4.png")));
       jButton1.setEnabled(true);
       jButton2.setEnabled(true);
       jButton3.setEnabled(true);
       jButton4.setEnabled(false);
       jButton5.setEnabled(true);
       jButton6.setEnabled(true);
       jButton7.setEnabled(true);
       jButton8.setEnabled(true);
       jButton9.setEnabled(false);
       jButton10.setEnabled(false);
       jButton12.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso5_1.png")));
       jButton1.setEnabled(true);
       jButton2.setEnabled(true);
       jButton3.setEnabled(true);
       jButton4.setEnabled(true);
       jButton5.setEnabled(false);
       jButton6.setEnabled(true);
       jButton7.setEnabled(true);
       jButton8.setEnabled(true);
       jButton12.setEnabled(true);
       
       //Atras-Siguiente
       button_number = 5;
       jButton9.setEnabled(true);
       jButton10.setEnabled(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso6_1.png")));
       jButton1.setEnabled(true);
       jButton2.setEnabled(true);
       jButton3.setEnabled(true);
       jButton4.setEnabled(true);
       jButton5.setEnabled(true);
       jButton6.setEnabled(false);
       jButton7.setEnabled(true);
       jButton8.setEnabled(true);
       jButton12.setEnabled(true);
       //Atras-Siguiente
       button_number = 6;
       jButton9.setEnabled(true);
       jButton10.setEnabled(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso8_1.png")));
       jButton1.setEnabled(true);
       jButton2.setEnabled(true);
       jButton3.setEnabled(true);
       jButton4.setEnabled(true);
       jButton5.setEnabled(true);
       jButton6.setEnabled(true);
       jButton7.setEnabled(true);
       jButton8.setEnabled(false);
       jButton12.setEnabled(true);
       button_number = 13;
       jButton9.setEnabled(true);
       jButton10.setEnabled(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso7_1.png")));
       jButton1.setEnabled(true);
       jButton2.setEnabled(true);
       jButton3.setEnabled(true);
       jButton4.setEnabled(true);
       jButton5.setEnabled(true);
       jButton6.setEnabled(true);
       jButton7.setEnabled(false);
       jButton8.setEnabled(true);
       jButton12.setEnabled(true);
       button_number = 7;
       jButton9.setEnabled(true);
       jButton10.setEnabled(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        System.out.println(button_number);
        //Atras boton 10
        if(button_number == 5){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso5_1.png")));
            jButton9.setEnabled(true);
            jButton10.setEnabled(false);
        }
        if(button_number == 6){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso6_1.png")));
            jButton9.setEnabled(true);
            jButton10.setEnabled(false);
        }
        if(button_number == 8){
            button_number = button_number - suma;
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso7_1.png")));
            jButton9.setEnabled(true);
            jButton10.setEnabled(false);
        }
        if(button_number == 9){
            button_number = button_number - suma;
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso7_2.png")));
            jButton9.setEnabled(true);
            jButton10.setEnabled(true);
        }
        if(button_number == 10){
            button_number = button_number - suma;
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso7_3.png")));
            jButton9.setEnabled(true);
            jButton10.setEnabled(true);
        }
        if(button_number == 11){
            button_number = button_number - suma;
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso7_4.png")));
            jButton9.setEnabled(true);
            jButton10.setEnabled(true);
        }
        if(button_number == 12){
            button_number = button_number - suma;
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso7_5.png")));
            jButton9.setEnabled(true);
            jButton10.setEnabled(true);
        }
        if(button_number == 14){
            button_number = button_number - suma;
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso8_1.png")));
            jButton9.setEnabled(true);
            jButton10.setEnabled(false);
        }
        if(button_number == 15){
            button_number = button_number - suma;
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso8_2.png")));
            jButton9.setEnabled(true);
            jButton10.setEnabled(true);
        }
        if(button_number == 16){
            button_number = button_number - suma;
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso8_3_1.png")));
            jButton9.setEnabled(true);
            jButton10.setEnabled(true);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        System.out.println(button_number);        
        // Siguiente
        if(button_number == 15){
            button_number = button_number + suma;
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso8_4.png")));
            jButton9.setEnabled(false);
            jButton10.setEnabled(true);
        }
        if(button_number == 14){
            button_number = button_number + suma;
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso8_3_1.png")));
            jButton9.setEnabled(true);
            jButton10.setEnabled(true);
        }
        if(button_number == 13){
            button_number = button_number + suma;
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso8_2.png")));
            jButton9.setEnabled(true);
            jButton10.setEnabled(true);
        }
        if(button_number == 11){
            button_number = button_number + suma;
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso7_6.png")));
            jButton9.setEnabled(false);
            jButton10.setEnabled(true);
        }
        if(button_number == 10){
            button_number = button_number + suma;
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso7_5.png")));
            jButton9.setEnabled(true);
            jButton10.setEnabled(true);
        }
        if(button_number == 9){
            button_number = button_number + suma;
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso7_4.png")));
            jButton9.setEnabled(true);
            jButton10.setEnabled(true);
        }
        if(button_number == 8){
            button_number = button_number + suma;
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso7_3.png")));
            jButton9.setEnabled(true);
            jButton10.setEnabled(true);
        }
        if(button_number == 7){
            button_number = button_number + suma;
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso7_2.png")));
            jButton9.setEnabled(true);
            jButton10.setEnabled(true);
        }
        if(button_number == 6){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso6_2.png")));
            jButton9.setEnabled(false);
            jButton10.setEnabled(true);
        }
        if(button_number == 5){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso5_2.png")));
            jButton9.setEnabled(false);
            jButton10.setEnabled(true);
        }
        System.out.println("ultimo "+button_number); 
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEF/foto_paso8_Neumann.png")));
       jButton1.setEnabled(true);
       jButton2.setEnabled(true);
       jButton3.setEnabled(true);
       jButton4.setEnabled(true);
       jButton5.setEnabled(true);
       jButton6.setEnabled(true);
       jButton7.setEnabled(true);
       jButton8.setEnabled(true);
       jButton12.setEnabled(false);
       jButton9.setEnabled(false);
       jButton10.setEnabled(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasosMEF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasosMEF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasosMEF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasosMEF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasosMEF().setVisible(true);
            }
        });
    }
    
    private int button_number = 1;
    private int suma = 1;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
